=== paulovlrs/TestAPI/src/Test/resources/schemas/postV2PetValidaCadastro.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "examples": [
    {
      "id": 9223127516080527788,
      "category": {
        "id": 0,
        "name": "Grande"
      },
      "name": "Brutus",
      "photoUrls": [
        "https://dnl7t01l0fo05.cloudfront.net/fr/wp-content/uploads/sites/2/2018/04/brutus-bullmastiff.jpg"
      ],
      "tags": [
        {
          "id": 0,
          "name": "Cachorro"
        }
      ],
      "status": "available"
    }
  ],
  "required": [
    "id",
    "category",
    "name",
    "photoUrls",
    "tags",
    "status"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The id schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        9223127516080527788
      ]
    },
    "category": {
      "$id": "#/properties/category",
      "type": "object",
      "title": "The category schema",
      "description": "An explanation about the purpose of this instance.",
      "default": {},
      "examples": [
        {
          "id": 0,
          "name": "Grande"
        }
      ],
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/category/properties/id",
          "type": "integer",
          "title": "The id schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "name": {
          "$id": "#/properties/category/properties/name",
          "type": "string",
          "title": "The name schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Grande"
          ]
        }
      },
      "additionalProperties": true
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The name schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Brutus"
      ]
    },
    "photoUrls": {
      "$id": "#/properties/photoUrls",
      "type": "array",
      "title": "The photoUrls schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          "https://dnl7t01l0fo05.cloudfront.net/fr/wp-content/uploads/sites/2/2018/04/brutus-bullmastiff.jpg"
        ]
      ],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/photoUrls/items",
        "anyOf": [
          {
            "$id": "#/properties/photoUrls/items/anyOf/0",
            "type": "string",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
              "https://dnl7t01l0fo05.cloudfront.net/fr/wp-content/uploads/sites/2/2018/04/brutus-bullmastiff.jpg"
            ]
          }
        ]
      }
    },
    "tags": {
      "$id": "#/properties/tags",
      "type": "array",
      "title": "The tags schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "id": 0,
            "name": "Cachorro"
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/tags/items",
        "anyOf": [
          {
            "$id": "#/properties/tags/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "id": 0,
                "name": "Cachorro"
              }
            ],
            "required": [
              "id",
              "name"
            ],
            "properties": {
              "id": {
                "$id": "#/properties/tags/items/anyOf/0/properties/id",
                "type": "integer",
                "title": "The id schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  0
                ]
              },
              "name": {
                "$id": "#/properties/tags/items/anyOf/0/properties/name",
                "type": "string",
                "title": "The name schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                  "Cachorro"
                ]
              }
            },
            "additionalProperties": true
          }
        ]
      }
    },
    "status": {
      "$id": "#/properties/status",
      "type": "string",
      "title": "The status schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "available"
      ]
    }
  },
  "additionalProperties": true
}

=== paulovlrs/TestAPI/src/Test/resources/requestBody/postV2Pet.json
{
  "id": 0,
  "category": {
    "id": 0,
    "name": "Grande"
  },
  "name": "Brutus",
  "photoUrls": [
    "https://dnl7t01l0fo05.cloudfront.net/fr/wp-content/uploads/sites/2/2018/04/brutus-bullmastiff.jpg"
  ],
  "tags": [
    {
      "id": 0,
      "name": "Cachorro"
    }
  ],
  "status": "available"
}
